### ISSUE TITLE
Release binary?

### ISSUE THREAD

**Issue by lynnux** [radareorg/r2ghidra#20] opened 2021-03-17 08:48 UTC
@trufae , hi, thank you for your hard work on radare2.
I want to use `pdg` on windows, but it seems building r2ghidra need a higher version of visual studio which support at least c++14 I think, but I only have vs2013, so I can't compile it at all (got many errors relate to c++ stuff).
So there has any plan to release binary?

**Comment by lynnux** [comment] 2021-03-17 10:09
After tried `clang-cl` with nmake, I succussfully build it out, but without `BUILD_SLEIGH_PLUGIN`(This will get `LoadImage` error).
And after set `SLEIGHHOME`, I finally get `pdg` work! Wow, so painful to make it work.

**Comment by trufae** [comment] 2021-03-17 10:22
Yes, I plan to fix the current CI before the next release (5.2) which may happen around April 1st. (not a joke :D)

How did you used nmake to build it? is this a supported backend by meson or cmake? are you using a release build of r2 or also building r2 from source to link r2ghidra against it? Would you like to try to fix the current w64 job?

Every release of r2 may have a binary build of r2ghidra for all the major platforms.

Ref: https://github.com/radareorg/r2ghidra/runs/2109333530?check_suite_focus=true
PD: My plan is to remove the cmake build system and just maintain acr and meson

**Comment by lynnux** [comment] 2021-03-18 02:29
I use cmake to generate the Makefile for nmake. I use the release from [https://github.com/radareorg/radare2/releases/tag/5.1.1](https://github.com/radareorg/radare2/releases/tag/5.1.1)
I don't know meson, but have some experience on cmake. I use cmake-gui to manually sepecific the `Radare2_INCLUDE_DIRS` and  `SDB_INCLUDE_DIR`, in CI you can try `cmake -GNinja .. -DRadare2_INCLUDE_DIRS=%CD%\..\radare2\include\libr -DSDB_INCLUDE_DIR=%CD%\..\radare2\include\libr\sdb`, this should be work.

**Comment by trufae** [comment] 2021-03-29 19:05
Fixed in master. i just pushed the last ci build for windows in https://github.com/radareorg/r2ghidra/releases/tag/v5.1.0

will publish debian and macOS packages when r2-5.2 is out

**Closed by trufae** 2021-03-29 19:05 UTC

**Comment by lynnux** [comment] 2021-04-06 09:02
Hi @trufae , today I tested r2ghidra-w64.zip, it's depends on:
![图片](https://user-images.githubusercontent.com/367894/113686179-907bfd00-96f9-11eb-86ef-a3c68d1f4744.png)
so I run get error:
![图片](https://user-images.githubusercontent.com/367894/113686296-b1445280-96f9-11eb-8df9-dae2e3b70fe7.png)

**Comment by trufae** [comment] 2021-04-06 09:31
thanks for testing! this dll is distributed with msvc and its the c++ runtime afaik, i have pushed a commit that makes cmake use /MT instead of /MD by default, so the next build should link this runtime statically in the plugins. The problem is that current windows build is done against the last r2 release (5.1.1) and i need to release r2-5.2 to fix the api changes (yeah, not going to add compile time support for pre-5.2 after this change). expect that to happen in a week
